version: '3.7'

services:
  backend:
    build: ./baobab-api
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./baobab-api/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./baobab-api/.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_dev

  frontend:
    hostname: localhost
    container_name: angular-container
    build: ./baobab-client
    ports:
      - 80:80
    volumes:
      - "/app/non_meodules"
      - ":/app"
volumes:
  postgres_data:
